version: 2
jobs:
  build:
    working_directory: ~/skript-mirror
    docker:
      - image: redis@sha256:54057dd7e125ca41afe526a877e8bd35ec2cdd33b9217e022ed37bdcf7d09673
    steps:
      - checkout
      - restore_cache:
          key: skript-mirror-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: skript-mirror-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew build
      - store_artifacts:
          path: build/libs/
