version: 2
jobs:
  build:
    working_directory: ~/skript-mirror
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: skript-mirror-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: skript-mirror-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew build
      - store_artifacts:
          path: build/libs/
          destination: /
